name: GitDonate Workflow

on:
  push:
    branches: [ main, master, upgrade-version-2.2.3.3 ]
    paths:
      - '.gitdonate/config.txt'
  schedule:
    # Run once a day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  update-donation-info:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install qrcode[pil] requests
        
    - name: Update donation information
      run: |
        # Extract BTC address from config
        if [ -f .gitdonate/config.txt ]; then
          BTC_ADDRESS=$(grep "btc_address" .gitdonate/config.txt | cut -d'=' -f2)
          
          # Generate QR code
          python gitdonate/generate_qr.py "$BTC_ADDRESS" ".gitdonate/btc_qr.png"
          
          # Update README.md
          python gitdonate/update_readme.py "README.md" "$BTC_ADDRESS"
          
          # Create DONATIONS.md
          python gitdonate/create_donations_md.py "DONATIONS.md" "$BTC_ADDRESS" ".gitdonate/btc_qr.png"
          
          echo "Donation information updated successfully"
        else
          echo "GitDonate config not found. Skipping update."
        fi
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if there are changes to commit
        if git diff --quiet; then
          echo "No changes to commit"
        else
          git add README.md DONATIONS.md assets/images/btc_qr.png
          git commit -m "Update donation information [skip ci]"
          git push
        fi
      
  # Optional: Monitor donations job
  # Uncomment to enable donation monitoring
  # monitor-donations:
  #   runs-on: ubuntu-latest
  #   needs: update-donation-info
  #   
  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v3
  #     
  #   - name: Set up Python
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: '3.10'
  #       
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install requests
  #       
  #   - name: Check for new donations
  #     run: |
  #       if [ -f .gitdonate/config.txt ]; then
  #         BTC_ADDRESS=$(grep "btc_address" .gitdonate/config.txt | cut -d'=' -f2)
  #         python gitdonate/monitor_donations.py --btc-address "$BTC_ADDRESS" --check-interval 60
  #       else
  #         echo "GitDonate config not found. Skipping donation check."
  #       fi
  #     env:
  #       EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
  #       EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
